sudo: false
language: ruby
notifications:
  email: false
rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
cache: bundler
before_install:
  - gem update --system
  - gem update bundler
script:
  - bundle exec rspec
